name: Trigger auto deployment for cliff-news

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cliff-news-AutoDeployTrigger-2364f506-fa20-4671-842a-156c1590c36d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIFFNEWS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLIFFNEWS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLIFFNEWS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CLIFFNEWS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLIFFNEWS_REGISTRY_PASSWORD }}
          containerAppName: cliff-news
          resourceGroup: finalProjRG
          imageToBuild: ghcr.io/cliff-news:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


