name: Build and Push to ACR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub Action runs on Ubuntu VM
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: cliffreg3.azurecr.io  # Your Azure Container Registry URL
        username: ${{ secrets.ACR_USERNAME }}  # Store Azure credentials in GitHub secrets
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t cliffreg3.azurecr.io/cliffbourne-chronicles:latest .
        docker push cliffreg3.azurecr.io/cliffbourne-chronicles:latest
